### PR TITLE
Fix icon

### PR DESCRIPTION
**Pull request by catsout**

### CODE REVIEW

**Comment by zocker-160** [comment]
is this distro / DE specific?

It works for me correctly on Kubuntu 20.04:
Screenshot_20220419_191135

**Comment by tinywrkb** [comment]
> is this distro / DE specific?
> 
> It works for me correctly on Kubuntu 20.04: Screenshot_20220419_191135



> is this distro / DE specific?
> 
> It works for me correctly on Kubuntu 20.04: Screenshot_20220419_191135

The [psudocode in the icon theme spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup) shows that the context (Applications, Mimetypes, Actions, ...) only matter for sorting order when searching for a suitable icon.  
So the suggested change shouldn't be needed if all application launchers were following the example, but I guess it's not the case. For example, I don't have a visible icon here with [fuzzel](https://codeberg.org/dnkl/fuzzel).  
That being said, it would be better to fix this in upstream.

**Comment by tinywrkb** [comment]
> is this distro / DE specific?
> 
> It works for me correctly on Kubuntu 20.04: Screenshot_20220419_191135



> is this distro / DE specific?
> 
> It works for me correctly on Kubuntu 20.04: Screenshot_20220419_191135

The [psudocode in the icon theme spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup) shows that the context (Applications, Mimetypes, Actions, ...) only matter for sorting order when searching for a suitable icon.  
So the suggested change shouldn't be needed if all application launchers were following the example, but I guess it's not the case. For example, I don't have a visible icon here with [fuzzel](https://codeberg.org/dnkl/fuzzel).  
That being said, it would be better to fix this in upstream.

**Comment by zocker-160** [comment]
@tinywrkb thank you for your answer, can you confirm that the icon does not show up also after a reboot? I know some DEs needs that.

If it does not work, I will merge this as a short term solution and look into fixing it upstream.

**Comment by tinywrkb** [comment]
@zocker-160 I'm using fuzzel with sway, no desktop environment, and no launcher related processes running in the background, so reboot will change nothing.  

In fact, I believe that fuzzel don't even care about `icon-theme.cache`, it only checks the first occurrence of `index.theme` (according to the spec), and the MimeTypes context is there, so the only problem is that it ignores the `MimeTypes` context associated subdir, see the [comparison here](https://codeberg.org/dnkl/fuzzel/src/tag/1.7.0/icon.c#L48).  

Installing the test build fixes the issue.

**Comment by zocker-160** [comment]
understood @tinywrkb, thank you for the explanation, I will merge this then

**Pull request merged**
