### PR TITLE
Beta runtime6.4

### PR DESCRIPTION
**Pull request by zocker-160**

### CODE REVIEW

**Comment by zocker-160** [comment]
Holy shit this protected branches bullshit is so fk annoying.

**Comment by dail8859** [comment]
> Project ERROR: Unknown module(s) in QT: core5compat

Not sure how to configure it to add this extra module but it is needed for Scintilla to compile on Qt6

**Comment by zocker-160** [comment]
hmmm

**Comment by zocker-160** [comment]
welp, will have to wait for https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/26 then ._.

**Comment by dail8859** [comment]
> welp, will have to wait for https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/26 then ._.

Sounds good. Thanks for giving it a shot at least.

**Comment by zocker-160** [comment]
@dail8859 it compiled o_O

**Comment by zocker-160** [comment]
It works fairly well actually. Theming is broken as expected, but it falls back to a default theme which I think is not bad at all.
It also does detect dark mode.

Screenshot_20230131_202243

**Comment by zocker-160** [comment]
There are a few things which are kinda weird but in general it does work, so I am merging into beta.

As for merging to stable, I would not do it if possible, but that is your call.

**Comment by dail8859** [comment]
> it compiled o_O

Nice! I guess it seems the qt5compat library is there already then.

> As for merging to stable, I would not do it if possible, but that is your call.

I agree holding off for now is fine. There were some nice fixes that Qt6 provided on Windows and MacOS but nothing I know of currently that Linux would benefit from. Although it is not ideal I'm fine sticking with Qt5 on Linux for now until either there is better support through flatpak or there is a very strong need to upgrade to Qt6.

**Comment by zocker-160** [comment]
> Nice! I guess it seems the qt5compat library is there already then.

Yes it got added into the runtime, but it was delayed as they had compilation issues which seem to have been fixed a week ago or so.

> Although it is not ideal I'm fine sticking with Qt5 on Linux for now until either there is better support through flatpak or there is a very strong need to upgrade to Qt6.

Makes sense, but even in the last case, it would work good enough I think, I did not encounter any breaking issues while testing.

**Pull request merged**
