### PR TITLE
Update NotepadNext.git to 0.5.1

### LINKED ISSUE #2: Enable wayland socket by default
This is just a small enhancement. I have noticed that `QT_QPA_PLATFORM` is set to `xcb` by default on the Flatpak image. The wayland socket is disabled by default as well, even though the application seems to support Wayland just fine which I have confirmed by setting QT_QPA_PLATFORM=wayland and enabling the wayland socket manually.
image

### LINKED ISSUE #3: Add `text/plain` MIME type to desktop entry
At the moment, I am unable to open files from an "Open With" dialog.

Commit https://github.com/dail8859/NotepadNext/commit/3477b35e484376c0bfa3331c7f8d1dc5305b39b5 adds the necessary MIME type support to open files from a dialog. I suggest to create a new release with this patch included, or patch the app with this commit.

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
This PR updates NotepadNext and adds adds flatpak-external-data-checker support for automatic update PRs (but manual merging process, for more info, check https://github.com/flathub/com.github.dail8859.NotepadNext/pull/4#issuecomment-1114097371.

Closes https://github.com/flathub/com.github.dail8859.NotepadNext/issues/2.
Closes https://github.com/flathub/com.github.dail8859.NotepadNext/issues/3.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by dail8859** [comment]
> adds adds flatpak-external-data-checker

If I understand this correctly it will watch the Notepad Next repository for releases and automatically update the yml file?

**Comment by TheEvilSkeleton** [comment]
Correct. However, the procedure goes as follows: flatpak-external-data-checker checks for updates. If there is an update, then it will update the yml manifest and submit a PR. The maintainer, in this case @zocker-160, will manually merge the PR when they want and/or can.

If they want to avoid the manual process, I can create a `flathub.json` file and tell the bot to merge the PR after it is submitted, with the following:

```json
{
   "automerge-flathubbot-prs": true
}
```

So, the difference here is that the bot will merge the PR an hour later the bot submits it.

**Comment by dail8859** [comment]
> then it will update the yml manifest and submit a PR

Awesome.

> If they want to avoid the manual process,

Manual is preferable for now.

**Comment by TheEvilSkeleton** [comment]
I marked it as draft so we can test and confirm that it works once it's built. It looks like there were already many apps in the queue, so we will have to wait a while for it to get started.

**Comment by zocker-160** [comment]
Sorry for my late response guys and thanks for the PR. It LGTM but it would be awesome if @TheEvilSkeleton could rebase this on top of the beta branch and pull request into master.

That way I can hit two birds with one stone and also fix #2 with one update.

**Review by zocker-160 — CHANGES_REQUESTED** [review]
Sorry for my late response guys and thanks for the PR. It LGTM but it would be awesome if @TheEvilSkeleton could rebase this on top of the beta branch.

That way I can hit two birds with one stone and also fix #2 with one update.

**Review by zocker-160 — APPROVED** [review]
LGTM thank you very much!

**Comment by dail8859** [comment]
@TheEvilSkeleton @zocker-160 Thanks!

**Pull request merged**
